# Generated by Django 4.0.1 on 2022-02-28 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swimming_pools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swimming_pool',
            name='author',
        ),
    ]
