# Generated by Django 4.0.1 on 2022-02-28 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swimming_pools', '0002_remove_swimming_pool_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimming_pool',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='swimmins_pools', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
