# Generated by Django 4.0.3 on 2022-04-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_remove_product_cost_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
