# Generated by Django 4.0.1 on 2022-02-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_rename_post_gym'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('gyms', models.ManyToManyField(to='gyms.Gym')),
            ],
        ),
    ]
