# Generated by Django 4.0.1 on 2022-02-11 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='address',
        ),
    ]
