# Generated by Django 4.0.1 on 2022-02-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_remove_gym_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
