# Generated by Django 4.0.1 on 2022-02-28 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gyms', '0005_gym_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gym',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gyms', to=settings.AUTH_USER_MODEL),
        ),
    ]
