# Generated by Django 4.0.1 on 2022-03-29 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gyms', '0006_alter_gym_address_alter_gym_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training_program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Сlient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.TextField()),
                ('weight', models.IntegerField()),
                ('external_id', models.IntegerField(blank=True, null=True)),
                ('age', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='gym',
            name='author',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='title',
        ),
        migrations.AddField(
            model_name='gym',
            name='square',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gym',
            name='address',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Сoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('route', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('clients', models.ManyToManyField(to='gyms.Сlient')),
                ('gyms', models.ManyToManyField(to='gyms.Gym')),
                ('training_programs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.training_program')),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gym',
            name='сoachs',
            field=models.ManyToManyField(to='gyms.Сoach'),
        ),
    ]
