# Generated by Django 4.0.1 on 2022-03-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0007_training_program_сlient_remove_gym_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gym',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='сoach',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
