# Generated by Django 4.0.1 on 2022-03-29 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0009_alter_сlient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сlient',
            name='external_id',
        ),
    ]
