# Generated by Django 4.0.1 on 2022-03-29 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0010_remove_сlient_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet', to='gyms.сoach'),
        ),
    ]
