# Generated by Django 4.0.1 on 2022-03-29 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0011_alter_diet_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_program',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='gyms.сoach'),
        ),
    ]
